name: pos
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+52
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_places_autocomplete_text_field:
    path: /Users/gianmarcodifrancesco/Work/google_places_autocomplete_text_field
  http: ^1.2.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  path_provider: ^2.1.2
  intl:
  auto_size_text: ^3.0.0
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_slidable: ^3.0.1
  share: ^2.0.4
  simple_animations: ^5.0.2
  url_launcher: ^6.2.4
  rflutter_alert: ^2.0.7
  sqflite:
#  device_preview: ^1.0.0
  internet_connection_checker:
  feature_discovery: ^0.14.1
#  firebase_crashlytics: ^2.5.05
  flutter_sticky_header: ^0.6.5
  package_info: ^2.0.2
  intro_slider: ^3.0.3
  material_design_icons_flutter: ^7.0.7296
  flip_card: ^0.6.0
  flutter_secure_storage: ^9.0.0
  dart_wom_connector:
    path: /Users/gianmarcodifrancesco/Work/Digit/Dart/dart_wom_connector
  logger:
  pdf: ^3.10.7
  barcode_widget: ^2.0.4
  hive:
  hive_flutter:
  modal_bottom_sheet: ^3.0.0-pre
  pull_to_refresh: ^2.0.0
  another_stepper: ^1.2.2
  loading_overlay:
  jwt_decoder: ^2.0.1

  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  flutter_codice_fiscale: ^0.0.3
  form_field_validator: ^1.1.0

  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  crop_your_image: ^0.7.5
  flutter_image_compress: ^2.1.0

  validatorless: ^1.2.3
  dio: ^5.4.0
  easy_localization: ^3.0.3
  easy_localization_loader:
  go_router:
  easy_rich_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/registry.pub
    - assets/registry_dev.pub
    - assets/logo_wom.png
    - assets/slide4.png
    - assets/translations/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: MerchantIcons
      fonts:
        - asset: fonts/MyFlutterApp.ttf